#!/bin/bash --login
# Enable strict mode.
set -euo pipefail
# ... Run whatever commands ...

# Temporarily disable strict mode and activate conda:
set +euo pipefail
conda activate python

# Re-enable strict mode:
set -euo pipefail

# exec the final command:
#exec jupyter notebook --ip=0.0.0.0s --allow-root --no-browser 
python -Xfaulthandler /workspace/inference.py -i speak1.txt -o /workspace/result/ --suffix wav --tacotron2=/workspace/models/tacotron2_1032590_6000_amp --waveglow=/workspace/models/waveglow_1076430_14000_amp --wn-channels 256 --fp16
#--fp16
exec "$@"
